# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-06 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_auto_20180611_1823'),
    ]

    operations = [
    ]


# CoreValuesAssessment
# partner = partner
# core_values_assessment_date = date
# core_values_assessment = attachment_file
# core_values_assessment_attachment = attachment
# archived = False