# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-06 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180703_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
